/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const addDialog: (typeof import("@/components/ReDialog"))["addDialog"]
  const closeAllDialog: (typeof import("@/components/ReDialog"))["closeAllDialog"]
  const closeDialog: (typeof import("@/components/ReDialog"))["closeDialog"]
  const updateDialog: (typeof import("@/components/ReDialog"))["updateDialog"]
}
